version: 2
jobs:
  build:

    working_directory: ~/test-deploy-12

    context: GITHUB_TOKEN

    docker:
      - image: circleci/openjdk:11-stretch

    steps:

      - checkout
      - run:
          name: "echo an env var that is part of our context"
          command: |
            echo $GITHUB_TOKEN
      - restore_cache:
          key: test-deploy-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: test-deploy-{{ checksum "pom.xml" }}
      - run: mvn clean
      - run: mvn -s .circleci/.circleci.settings.xml deploy

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/test-deploy-1.0-SNAPSHOT.jar