version: 2.1


jobs:
  build:

    working_directory: ~/test-deploy

    docker:
      - image: circleci/openjdk:11-stretch

    steps:

      - checkout

      - restore_cache:
          key: test-deploy-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: test-deploy-{{ checksum "pom.xml" }}


      - run: mvn clean

      - run: mvn -s .circleci/.circleci.settings.xml deploy

      - store_test_results:
          path: target/surefire-reports/test_result.html

      - store_artifacts:
          path: target/surefire-reports/test_report.html

  generate_test_result:

    working_directory: ~/test-deploy

    docker:
      - image: circleci/openjdk:11-stretch

    steps:
      - run: mvn surefire-report:report-only

workflows:
  workflow:
    jobs:
      - build:
          context: GITHUB_TOKEN
          post-steps:
            - run: mvn surefire-report:report-only



