
version: 2
jobs:
  build:

    working_directory: ~/ circleci-maven-package-deploy

    docker:
      - image: circleci/openjdk:11-stretch

    steps:

      - checkout

      - restore_cache:
          key:  circleci-maven-package-deploy-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key:  circleci-maven-package-deploy-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/ circleci-maven-package-deploy-1.0-SNAPSHOT.jar